languages:
  JavaScript: true
engines:
  eslint:
    enabled: true
ratings:
  paths:
  - "src/js/**"
exclude_paths:
- "__mocks__/**/*"
- "tests/**/*"
- "utils/**/*"
- "/build/**/*"
- "/plugins/**/*"
- "/config/**/*"
